# Pandas

In [2]:
import pandas as pd

In [7]:
#check panda version
print(pd.__version__)
print(pd.__file__)

1.0.1
C:\Users\user\anaconda3\lib\site-packages\pandas\__init__.py


In [13]:
#create series of values with index using panda
#Method 1
#Passing explicit data
A = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(A.values)
print(A.index)
print(type(A.values))#its numpy array
print(type(A))#it is panda type. so using numpy values panda can be developed

[1 2 3 4 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [14]:
#Accessing values using indices, like in dictionary
print(A['a'])

1


In [16]:
#Slicing
A['a':'d']#the result includes d also
          #when we are using explicit indices, the last value also included

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
#Create series of values with index using panda
#Method 2
#Create dict and Passing Dictionary to panda series method
dict = {'A':4,'A-':3.5,'B-':2.5,'B':2}
grades = pd.Series(dict)
print(grades.values)

dict1 = {'A':85,'A-':80,'B-':75,'B':65}
marks = pd.Series(dict1)
print(marks)

[4.  3.5 2.5 2. ]
A     85
A-    80
B-    75
B     65
dtype: int64


In [5]:
marks['A']

85

In [6]:
print(marks[0:2])#implicit index. it wont include last item

print(marks['A':'B'])#explicit index. it will include last item

A     85
A-    80
dtype: int64
A     85
A-    80
B-    75
B     65
dtype: int64


In [9]:
grades

A     4.0
A-    3.5
B-    2.5
B     2.0
dtype: float64

In [10]:
marks

A     85
A-    80
B-    75
B     65
dtype: int64

In [13]:
df = pd.DataFrame({'Grades':grades,'Marks':marks})

In [14]:
df

Grades  Marks
A      4.0     85
A-     3.5     80
B-     2.5     75
B      2.0     65

In [15]:
marks

A     85
A-    80
B-    75
B     65
dtype: int64

In [16]:
grades

A     4.0
A-    3.5
B-    2.5
B     2.0
dtype: float64

In [19]:
#we can transpose dataframe
df.T

A    A-    B-     B
Grades   4.0   3.5   2.5   2.0
Marks   85.0  80.0  75.0  65.0

In [20]:
df

Grades  Marks
A      4.0     85
A-     3.5     80
B-     2.5     75
B      2.0     65

In [21]:
#Acceesing data
df.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 2.5, 75. ],
       [ 2. , 65. ]])

In [22]:
df.values[2,0]

2.5

In [23]:
df.columns

Index(['Grades', 'Marks'], dtype='object')

In [24]:
df.index

Index(['A', 'A-', 'B-', 'B'], dtype='object')

In [25]:
df.values[2,:]

array([ 2.5, 75. ])

In [27]:
df['percentage'] = df['Marks']/100

In [28]:
df

Grades  Marks  percentage
A      4.0     85        0.85
A-     3.5     80        0.80
B-     2.5     75        0.75
B      2.0     65        0.65

In [29]:
df['scaledMarks'] = 90*(df['Marks']/100) 

In [30]:
df

Grades  Marks  percentage  scaledMarks
A      4.0     85        0.85         76.5
A-     3.5     80        0.80         72.0
B-     2.5     75        0.75         67.5
B      2.0     65        0.65         58.5

In [31]:
#To delete a column
del df['percentage']

In [32]:
df

Grades  Marks  scaledMarks
A      4.0     85         76.5
A-     3.5     80         72.0
B-     2.5     75         67.5
B      2.0     65         58.5

In [33]:
#MAsking can be done
G = df[df['Marks']>70]

In [34]:
G

Grades  Marks  scaledMarks
A      4.0     85         76.5
A-     3.5     80         72.0
B-     2.5     75         67.5

In [36]:
#Handling Missing Values
#For example pass list of dict to create dataframe
A = pd.DataFrame([{'a':1,'b':4},{'b':3,'c':9}])
A

a  b    c
0  1.0  4  NaN
1  NaN  3  9.0

In [38]:
#Handling Missing Values - Method 1
#Fill NaN with zero
A.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0  3  9.0

In [40]:
#Handling Missing Values - Method 2
A.dropna? #To drop all  issing value records

# Pandas (Indexing)

In [44]:
#Explicit and implicit indexing confusion
A = pd.Series(['a','b','c'],index=[1,3,5])
A

1    a
3    b
5    c
dtype: object

In [45]:
A[1]#explicit indexing

'a'

In [46]:
 A[1:3]#implicit indexing, but we may expect a and b

3    b
5    c
dtype: object

In [47]:
A.loc[1:3]#using loc method, we use explicit indexing

1    a
3    b
dtype: object

In [49]:
A.iloc[1:3]#iloc for implicit indexing

3    b
5    c
dtype: object

In [50]:
df

Grades  Marks  scaledMarks
A      4.0     85         76.5
A-     3.5     80         72.0
B-     2.5     75         67.5
B      2.0     65         58.5

In [51]:
df1 = df

In [52]:
df1

Grades  Marks  scaledMarks
A      4.0     85         76.5
A-     3.5     80         72.0
B-     2.5     75         67.5
B      2.0     65         58.5

In [55]:
del df1['scaledMarks']

In [56]:
df1

Grades  Marks
A      4.0     85
A-     3.5     80
B-     2.5     75
B      2.0     65

In [57]:
df1.iloc[2,:]

Grades     2.5
Marks     75.0
Name: B-, dtype: float64