# 1. Write a NumPy program to print the NumPy version in your system.

In [1]:
import numpy as np
print(np.__version__)


1.18.1


# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [3]:
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [4]:

import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


# 5. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [7]:
A = np.arange(12,38)
print(A)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# 6. Write a NumPy program to reverse an array (first element becomes last). 
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [17]:
A = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37] 
print(A[::-1])

[37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


# 7. Write a NumPy program to convert an array to a float type. 
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [19]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)#asfarray to convert an array to float type
print("Array converted to a float type:")
print(x)


Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [30]:
#Hurray!!!
A = np.ones(30).reshape(6,5)
print(A)
A[1:-1,1:-1] = 0
print()
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [49]:

x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")

x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [59]:
A = np.zeros(64).reshape(8,8)
print(A)

A[1::2,::2] = 1
A[::2,1::2] = 1
print()
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 11. Write a NumPy program to convert a list and tuple into arrays. 
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [60]:

my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


# 12. Write a NumPy program to append values to the end of an array. Go to the editor
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [61]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


# 13. Write a NumPy program to create an empty and a full array. Go to the editor
Expected Output:
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
[[6 6 6]
[6 6 6]
[6 6 6]]

In [63]:
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x) # prints Garbage Value
# Create a full array
y = np.full((3,3),6)
print(y)


[[4.24399158e-314 8.48798317e-314 1.27319747e-313 1.69759663e-313]
 [2.12199579e-313 2.54639495e-313 2.97079411e-313 3.39519327e-313]
 [3.81959242e-313 4.24399158e-313 4.66839074e-313 5.09278990e-313]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


# 25. Write a NumPy program to construct an array by repeating. Go to the editor

Sample array: [1, 2, 3, 4]
Expected Output:
Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]

In [90]:
A = [1,2,3,4]
def repeat(A,n):
    B = []
    for i in range(n):
        B = np.append(A,B)
    return np.array(B)
    
print(repeat(A,3))
print()

#OR
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)


[1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4.]

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


# 26. Write a NumPy program to repeat elements of an array. 
Expected Output:
[3 3 3 3]
[1 1 2 2 3 3 4 4]

In [9]:
import numpy as np
A = np.repeat(3,4)

B = np.repeat([1,2,3,4],2)
C = np.repeat([[1,2],[3,4]],2)

print(A)
print(B)
print(C)

[3 3 3 3]
[1 1 2 2 3 3 4 4]
[1 1 2 2 3 3 4 4]


# 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array. Go to the editor
Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0

In [14]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: \n",x)

print("\nMaximum Values: ",np.max(x))
print("Minimum Values: ",np.min(x))

print("\nMaximum Values: ",np.argmax(x))#argmax - to get the indices
print("Minimum Values: ",np.argmin(x))

Original array: 
 [1 2 3 4 5 6]

Maximum Values:  6
Minimum Values:  1

Maximum Values:  5
Minimum Values:  0


# 28. Write a NumPy program compare two given arrays. Go to the editor
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [15]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))


Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


# 29. Write a NumPy program to sort an along the first, last axis of an array. Go to the editor
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]

In [19]:

a = np.array([[4, 6],[2, 1]])
print("\nOriginal array: ")
print(a)
print("\nSort along the first axis: ")#Sort column wise
x = np.sort(a, axis=0)
print(x)
print("\nSort along the last axis: ")#Sort row wise
y = np.sort(x, axis=1)
print(y)



Original array: 
[[4 6]
 [2 1]]

Sort along the first axis: 
[[2 1]
 [4 6]]

Sort along the last axis: 
[[1 2]
 [4 6]]


# 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array. Go to the editor
Original array:
[[ 0 10 20]
[20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [29]:
#np.nonzero - Return the indices of the elements that are non-zero.
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [30]:
import numpy as np
print("Create an array of zeros")

x = np.zeros((1,2))

print("Default type is float")
print(x)
print("Type changes to int")

x = np.zeros((1,2), dtype = np.int)

print(x)
print("Create an array of ones")

y= np.ones((1,2)) 

print("Default type is float")
print(y)
print("Type changes to int")

y = np.ones((1,2), dtype = np.int)

print(y)


Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


# 38. Write a NumPy program to create a new shape to an array without changing its data. Go to the editor
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [31]:

x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


# 39. Write a NumPy program to change the data type of an array. Go to the editor
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [32]:

x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)


[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
