# 1. Write a NumPy program to get the numpy version and show numpy build configuration

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

# 2.Write a NumPy program to  get help on the add function

In [10]:
#np.add? - np.method_name? we can type method name with question mark
#or
#help(np.add) - we can pass as an argument also
#same way, we can get help on any method
#example

A1 = [1,2,3]
A2 = [2,3,4]
A3 = np.add(A1,A2)
print(A3)

[3 5 7]


# 3.Write a NumPy program to test whether none of the elements of a given array is zero.

In [40]:
A = np.array([1,2,3,4,5,6])
B = np.array([4,5,6,7,8,0])
#Using Logic
count = 0
for i in A:
    if(i==0):
        print("This array contains zero")
        break
    else:
        count=count+1
        if count==len(A):
            print("The array contains no zero elements") 
            
#Using Built in Method            
print("Using built in Method np.all(x)")
print("Array A contains no Zero-",np.all(A))
print("Array B contains no Zero-",np.all(B))

The array contains no zero elements
Using built in Method np.all(x)
Array A contains no Zero- True
Array B contains no Zero- False


# 4.Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [44]:
C = np.array([0,0,0,0,0])
D = np.array([1,2,0,0,0])

print("The given C array contains any non-zero elements")
print(np.any(C))

print("The given D array contains any non-zero elements")
print(np.any(D))

The given C array contains any non-zero elements
False
The given D array contains any non-zero elements
True


# 5.Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [47]:
C = np.array([10,23,34,67,87])
D = np.array([1,2,np.inf,27,np.nan])

print("The given C array details")
print(np.isfinite(C))

print("The given D array details")
print(np.isfinite(D))

The given C array details
[ True  True  True  True  True]
The given D array details
[ True  True False  True False]


# 6.Write a NumPy program to test element-wise for positive or negative infinity.

In [13]:
A = np.array([12, 34, np.inf, np.nan])
B = np.array([12,13,45,23])

print("Original A Array\n",A)
print("\nOriginal B Array\n",B)

print("\nTest element-wise for positive or negative infinity-Array A")
print(np.isinf(A))

print("\nTest element-wise for positive or negative infinity-Array B")
print(np.isinf(B))

Original A Array
 [12. 34. inf nan]

Original B Array
 [12 13 45 23]

Test element-wise for positive or negative infinity-Array A
[False False  True False]

Test element-wise for positive or negative infinity-Array B
[False False False False]


# 7.Write a NumPy program to test element-wise for NaN of a given array.

In [16]:
A = ([1,2,3,np.nan,np.inf])
print("\n Original Array", A)
print("\nest element-wise for NaN of a given array")
print("\n",np.isnan(A))


 Original Array [1, 2, 3, nan, inf]

est element-wise for NaN of a given array

 [False False False  True False]


# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [22]:
A = np.array([1+3j,2,3+2j,4,5,6+1j])
print("Original Array\n",A)

print("\nType is",type(A))

print("\nCheck element wise complex number")
print("\n",np.iscomplex(A))
print("\nCheck element wise Real number")
print("\n",np.isreal(A))
print("\n", np.isscalar(4.3))
print(np.isscalar([4.3]))

Original Array
 [1.+3.j 2.+0.j 3.+2.j 4.+0.j 5.+0.j 6.+1.j]

Type is <class 'numpy.ndarray'>

Check element wise complex number

 [ True False  True False False  True]

Check element wise Real number

 [False  True False  True  True False]

 True
False


# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerancet
#It returns True or False by comparing all elemets one by one

In [33]:
#np.allclose - this method checks all elements one by one. if difference is upto tolerance level, then it will return TRUE
A = np.array([1,2,3,4,5])
B = np.array([1.01,2.01,3,4,5])
print("\n",np.allclose(A,B))
      
A1 = np.array([1,2,3,4,5])
B1 = np.array([1.00001,2.000001,3,4,5])
print("\n",np.allclose(A1,B1))

A2 = np.array([1,2,np.nan,5])
B2 = np.array([1,2,np.nan,5])
print("\n",np.allclose(A2,B2))

#We have to mention np.nan as TRUE. then it will consider as equal value
A2 = np.array([1,2,np.nan,5])
B2 = np.array([1,2,np.nan,5])
print("\n",np.allclose(A2,B2,equal_nan = True))


 False

 True

 False

 True


# 10.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [41]:
A = np.array([8,2,3,4,5,7])
B = np.array([1,3,4,5,6,7])
print("\nCheck for A>B",np.greater(A,B))
print("\nCheck for A>=B",np.greater_equal(A,B))
print("\nCheck for A<B",np.less(A,B))
print("\nCheck for A<=B",np.less_equal(A,B))


Check for A>B [ True False False False False False]

Check for A>=B [ True False False False False  True]

Check for A<B [False  True  True  True  True False]

Check for A<=B [False  True  True  True  True  True]


# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [45]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:\n")
print(x)
print(y)
print("\nElement Wise Comparison - equal:")
print(np.equal(x, y))
print("\nOver all Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:

[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]

Element Wise Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]

Over all Comparison - equal within a tolerance:
True


# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [56]:
A = np.array([1,7,14,105])

print("The size of array A is", np.size(A))
print("The length of array A is", len(A))
print("Each item size of array A is", A.itemsize)
print("\n%d bytes" % (A.size * A.itemsize))

The size of array A is 4
The length of array A is 4
Each item size of array A is 4

16 bytes


# 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [58]:
A = np.zeros(10)
print("Zeros array",A)

B = np.ones(10)
print("\nOnes array",B)

C = np.ones(10)*5
print("\nMultiples of Ones array",C)

D = np.ones(10)*8
print("\nMultiples of Ones array",D)

Zeros array [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Ones array [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Multiples of Ones array [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

Multiples of Ones array [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


# 14. Write a NumPy program to create an array of the integers from 30 to70.

In [61]:
#We can mention Array Range using arange() method

A = np.arange(30,71)
print(A)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 15. Write a NumPy program to create an array of all the even integers from 30 to 70

In [63]:
A = np.arange(30,71,2)
print(A)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 16. Write a NumPy program to create a 3x3 identity matrix

In [65]:
A = np.identity(3)
print("The 3*3 Identiti matrix is\n",A)

The 3*3 Identiti matrix is
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 17. Write a NumPy program to generate a random Integer

In [84]:
#randint(low, high=None, size=None, dtype='l')

print("\n Any Random integer below 3")
A = np.random.randint(3)
print(A)
#Return random integer below 3

print("\n Any Random integer 3 to 5")
B = np.random.randint(3,5)
print(B)


print("\nRandom integers with the dimension 2*3 from 30 to 100")
C = np.random.randint(30,100,(2,3))
print(C)

print("\nRandom integers with the dimension 2*3 from 30 to 100 with data type mentioned")
D = np.random.randint(30,100,(2,3),dtype='int')
print(D)

print("\n Data Type is",D.dtype)


 Any Random integer below 3
1

 Any Random integer 3 to 5
3

Random integers with the dimension 2*3 from 30 to 100
[[41 33 66]
 [44 78 87]]

Random integers with the dimension 2*3 from 30 to 100 with data type mentioned
[[43 51 95]
 [47 75 76]]

 Data Type is int32


# 18.Write a NumPy program to generate a random number between 0 and 1.

In [7]:
#np.random.normal?
#np.random.normal(loc=0.0, scale=1.0, size=None)
#loc: Mean ("centre") of the distribution
#scale: Standard deviation (spread or "width") of the distribution
A = np.random.normal(0,1,1)
print(A)

A1 = np.random.normal(0,100,1)
print("\n",A1)

A2 = np.random.normal(0,1,(2,2))
print("\n",A2)

[-0.90116354]

 [-123.27748371]

 [[ 3.43654237  0.86818906]
 [-0.26773565  0.12539156]]


# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [22]:
#arange([start,] stop[, step,], dtype=None)
S = np.arange(15,60,3)
print(S)
A = np.arange(15,55)
print("\nOriginal vector:")
print("\n",A)
print("\nAll values except the first and last of the said vector:")
print("\n",A[1:-1])

[15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]

Original vector:

 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]

All values except the first and last of the said vector:

 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


# 20. Write a NumPy program to create a 3X4 array using and iterate over it.

In [41]:

a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)


print("\nIterate using for loop. It will iterate row wise")
for i in a:
    print("\n",i)

    
print("\nIterate using np.nditearte. It will access each element of the array")
for i in np.nditer(a): #n dimensional iterator
    print(i,end=" ") #if we didnt give end ="", then it will print in new line


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Iterate using for loop. It will iterate row wise

 [10 11 12 13]

 [14 15 16 17]

 [18 19 20 21]

Iterate using np.nditearte. It will access each element of the array
10 11 12 13 14 15 16 17 18 19 20 21 

# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [50]:
#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`]. Default num value is 50 or we can mention


v = np.linspace(5, 50, 10)#start,stop,num

print("Length 10 with values evenly distributed between 5 and 50:\n")
print(v)

Length 10 with values evenly distributed between 5 and 50:

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [59]:
#arange([start,] stop[, step,], dtype=None)

A = np.arange(0,21)
print("Original vector:")
print(A)


print("\nAfter changing the sign of the numbers in the range from 9 to 15:")
A[(A>=9) & (A<=15)] *=-1
print(A)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


# 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [63]:
A = np.linspace(0,10,5)
print(A)

#or

#randint(low, high=None, size=None, dtype='l')
x = np.random.randint(0, 11, 5)
print("\nVector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)


[ 0.   2.5  5.   7.5 10. ]

Vector of length 5 filled with arbitrary integers from 0 to 10:
[2 4 6 9 0]


# 24. Write a NumPy program to multiply the values of two given vectors.

In [66]:
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)

y= np.random.randint(0, 11, 4)
print("\nVector-2")
print(y)

result = x * y
print("\nMultiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]

Vector-2
[8 7 4 3]

Multiply the values of two said vectors:
[ 8 56 12 15]


# 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. 

In [69]:
A = np.arange(10,22).reshape(3,4)
print(A)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# 26. Write a NumPy program to find the number of rows and columns of a given matrix. 

In [74]:
m= np.arange(10,22).reshape((3, 4))
print("Original matrix:")
print(m)

print("\nNumber of rows and columns of the said matrix:")
print(m.shape)
#Other array properties
print(m.itemsize) #each item size
print(m.dtype) #data type
print(m.size) #total size
print(m.ndim) #dimension

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Number of rows and columns of the said matrix:
(3, 4)
4
int32
12
2


# 27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 

In [78]:
#np.identity(n, dtype=None)
A = np.identity(3)
print(A)

#or

A = np.eye(3)
print("\n",A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0. 

In [79]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. 

In [92]:
#Method 1
x = np.zeros((5, 5))
y= np.array([1,2,3,4,5])

np.fill_diagonal(x,y)
print(x)

#Method 2
A = np.diag([1, 2, 3, 4, 5])
print("\n",A)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]

 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

#https://medium.com/@melodyxu/the-confusing-double-colon-in-numpy-850093adc36f#:~:text=This%20means%20starting%20from%20index,six%20and%20skip%20by%202. Slicing very good Article

In [104]:
A = np.zeros((4,4))
print(A)

A[::2, 1::2] = 1
A[1::2, ::2] = 1


print("\n",A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# 31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values. 

In [112]:
#randint(low, high=None, size=None, dtype='l')
A = np.random.randint(10,39,(3,3,3)) #returns integer values from given range
print("\n",A)

#or
#random(size=None)
B = np.random.random((3,3,3)) #return random values in 0 - 1 Range
print("\n",B)



 [[[36 26 33]
  [36 32 37]
  [13 15 26]]

 [[21 29 11]
  [24 25 11]
  [32 21 29]]

 [[33 14 11]
  [17 24 11]
  [12 19 26]]]

 [[[0.13119385 0.28388043 0.3815084 ]
  [0.2264928  0.52482431 0.66152745]
  [0.27697115 0.57951674 0.71190197]]

 [[0.78590254 0.39641428 0.52493025]
  [0.93340977 0.94106072 0.01362755]
  [0.14706407 0.94133514 0.79499682]]

 [[0.02805791 0.18943877 0.71175375]
  [0.1746477  0.65790317 0.84011798]
  [0.91655153 0.05905564 0.32352576]]]


# 32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array. 

In [114]:
#np.sum-Sum of array elements over a given axis.
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)

print("Sum of all elements:")
print(np.sum(x))

print("Sum of each column:")
print(np.sum(x, axis=0))

print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


# 33. Write a NumPy program to compute the inner product of two given vectors. 

In [116]:
x = np.array([4, 5])
y = np.array([7, 10])

print("Original vectors:")
print(x)
print(y)

print("Inner product of said vectors:")
print(np.dot(x, y)) #returns sum of row wise products

print(x*y) # Shows only row wise product,not sum


Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
[28 50]


# 34. Write a NumPy program to add a vector to each row of a given matrix.

In [128]:

m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)

result = np.empty_like(m)

for i in range(4): #range gives 0 to 3
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)


Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


# 35. Write a NumPy program to save a given array to a binary file . 

In [129]:
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print("Check if 'temp_arra.npy' exists or not?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

Check if 'temp_arra.npy' exists or not?
True
